name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Build with Gradle DebugApp
      run: ./gradlew assembleDebug
    - name: Find apk file
      run: find ./ -type f -name "*.apk"


    - name: Upload APK
      uses: actions/upload-artifact@v4   # Update to v4
      with:
        name: chatgptapp
        path: app/build/outputs/apk/debug/app-debug.apk

#    - name: Compress files
 #     run: tar -czvf archive.tar.gz ~/.gradle/caches/transforms-2/files-2.1/*/support-compat-28.0.0

  #  - name: Upload archive.tar.gz
   #   uses: actions/upload-artifact@v4
    #  with:
     #   name: android-support
      #  path: ./archive.tar.gz
